//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoWHeadParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoWHeadParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to stop ?.
        /// </summary>
        internal static string AbortQuestion {
            get {
                return ResourceManager.GetString("AbortQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entries count: {0}.
        /// </summary>
        internal static string EntryCountLabel {
            get {
                return ResourceManager.GetString("EntryCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get response from {0}.
        /// </summary>
        internal static string Error_Cannot_get_response {
            get {
                return ResourceManager.GetString("Error_Cannot_get_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get loader for {0} file.
        /// </summary>
        internal static string Error_unsupported_db_file_loader {
            get {
                return ResourceManager.GetString("Error_unsupported_db_file_loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading {0}! Skip.
        /// </summary>
        internal static string Error_while_loading_db_file {
            get {
                return ResourceManager.GetString("Error_while_loading_db_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading last locale from settings! Last locale index &lt; locales count!.
        /// </summary>
        internal static string Error_while_loading_last_locale {
            get {
                return ResourceManager.GetString("Error_while_loading_last_locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading last parser from settings! Last parser index &lt; parsers count!.
        /// </summary>
        internal static string Error_while_loading_last_parser {
            get {
                return ResourceManager.GetString("Error_while_loading_last_parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading welf file {0} - {1}.
        /// </summary>
        internal static string Error_while_loading_welf_file {
            get {
                return ResourceManager.GetString("Error_while_loading_welf_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to quit WoWHead Parser ?.
        /// </summary>
        internal static string ExitQuestion {
            get {
                return ResourceManager.GetString("ExitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting....
        /// </summary>
        internal static string Label_Abort {
            get {
                return ResourceManager.GetString("Label_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete!.
        /// </summary>
        internal static string Label_Complete {
            get {
                return ResourceManager.GetString("Label_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing....
        /// </summary>
        internal static string Label_Working {
            get {
                return ResourceManager.GetString("Label_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} db files in {1} ms.
        /// </summary>
        internal static string Loaded_count_db_files {
            get {
                return ResourceManager.GetString("Loaded_count_db_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting value can not be bigger than ending value!.
        /// </summary>
        internal static string MultipleTypeBigger {
            get {
                return ResourceManager.GetString("MultipleTypeBigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting value can not be equal ending value!.
        /// </summary>
        internal static string MultipleTypeEqual {
            get {
                return ResourceManager.GetString("MultipleTypeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found!.
        /// </summary>
        internal static string WelfFileNotFound {
            get {
                return ResourceManager.GetString("WelfFileNotFound", resourceCulture);
            }
        }
    }
}
